In [1]:
import numpy as np

In [3]:
#Creating numpy array using different method
array_from_list=np.array([1,2,3,4,5])
print (array_from_list)

[1 2 3 4 5]


In [5]:
#creating array filled with zeros
array_zeros=np.zeros(10)
print(array_zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#Creating an array filled with range of values
array_arange=np.arange(1,10)
print(array_arange)

[1 2 3 4 5 6 7 8 9]


In [14]:
#performing mathematical operation on numpy
array_a=np.array([1,2,3,4,5,6,7])
array_b=np.array([45,67,2,3,45,7,0])
numpy_add=array_a+array_b
print(numpy_add)

#numpy multiplication 
numpy_multiplication=array_a*array_b
print(numpy_multiplication)

#numpy Subtraction 
numpy_substraction=array_a-array_b
print(numpy_substraction)

#numpy Division 
numpy_dev=array_a/array_b
print(numpy_dev)

[46 69  5  7 50 13  7]
[ 45 134   6  12 225  42   0]
[-44 -65   1   1 -40  -1   7]
[0.02222222 0.02985075 1.5        1.33333333 0.11111111 0.85714286
        inf]


C:\Users\KIIT\AppData\Local\Temp\ipykernel_11936\3203916302.py:16: RuntimeWarning: divide by zero encountered in divide
  numpy_dev=array_a/array_b


In [18]:
#indexing and slicing
array_c=np.array([23,45,67,89,23,12])
print(array_c)
print(array_c[2])
print(array_c[1:4])

[23 45 67 89 23 12]
67
[45 67 89]


In [20]:
#Statistical Analysis
array_mean=print(np.mean(array_c))

43.166666666666664


In [22]:
#Find out the median of array elements
array_median=print(np.median(array_c))

#find out the mode of array elements given
array_mode=print (np.argmax(np.bincount(array_c)))

34.0
23


In [24]:
#reshaping Array
array_reshaped=array_c.reshape((1,6))
print(array_reshaped)

array_transposed=array_reshaped.T
print(array_transposed)

[[23 45 67 89 23 12]]
[[23]
 [45]
 [67]
 [89]
 [23]
 [12]]


In [25]:
'''create an 1D array with elements from 1 to 5. also create a 2D array with shape(3,3) 
filled with zeros.'''

# Create a 1D array with elements from 1 to 5
one_d_array = np.arange(1, 6)

# Create a 2D array with shape (3, 3) filled with zeros
two_d_array = np.zeros((3, 3))

# Print the arrays
print("1D array:", one_d_array)
print("2D array:\n", two_d_array)


1D array: [1 2 3 4 5]
2D array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
'''Take 2 Array and perform element wise addition and subtractions.'''

# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Perform element-wise addition and subtraction
addition = array1 + array2
subtraction = array1 - array2

# Print the results
print("Element-wise addition:\n", addition)
print("Element-wise subtraction:\n", subtraction)


Element-wise addition:
 [ 7  9 11 13 15]
Element-wise subtraction:
 [-5 -5 -5 -5 -5]


In [27]:
'''create an array [2,4,6,8,10] and print the elements at evene indices.'''

# Create an array with elements from 2 to 10
arr = np.arange(2, 11, 2)

# Print elements at even indices (0, 2, 4)
print("Elements at even indices:", arr[::2])


Elements at even indices: [ 2  6 10]


In [28]:
''' Calculate the sum of all the elements in a 2D array.'''

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the sum of all elements
sum_of_elements = np.sum(arr)

# Print the sum
print("Sum of all elements:", sum_of_elements)


Sum of all elements: 45


In [29]:
'''.Create a 1D array and reshape the array into 2D array with shape(2,3) .
Transpose a 2D array'''

# Create a 1D array
arr = np.arange(1, 7)  # Elements from 1 to 6

# Reshape the array into 2D with shape (2, 3)
reshaped_arr = arr.reshape(2, 3)

# Print the reshaped array
print("Reshaped array:\n", reshaped_arr)

# Transpose the 2D array
transposed_arr = reshaped_arr.T

# Print the transposed array
print("Transposed array:\n", transposed_arr)


Reshaped array:
 [[1 2 3]
 [4 5 6]]
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]


In [30]:
''' Generate a random array of integers between 1 to 10. create an array of random floats
and round them off to the nearest integer.'''

# Generate a random array of integers between 1 and 10
random_integers = np.random.randint(1, 11, size=10)  # Generate 10 random integers

# Create an array of random floats
random_floats = np.random.rand(10)  # Generate 10 random floats between 0 and 1

# Round the floats to the nearest integer
rounded_integers = np.round(random_floats)

# Print the arrays
print("Random integers:\n", random_integers)
print("Random floats:\n", random_floats)
print("Rounded integers:\n", rounded_integers)


Random integers:
 [ 2  6  4  1 10  9  5  7  4 10]
Random floats:
 [0.16473834 0.25900437 0.84179093 0.62859767 0.13137724 0.73355081
 0.03114332 0.59166415 0.1994907  0.73623015]
Rounded integers:
 [0. 0. 1. 1. 0. 1. 0. 1. 0. 1.]


In [31]:
'''Create an array of numbers and apply custom mathematical operations as square root exponential.'''

def custom_operation(x):
  """
  This function performs the custom mathematical operation of square root exponential.
  Args:
    x: A numerical value.
  Returns:
    The square root of the exponential of x.
  """
  return np.sqrt(np.exp(x))

# Create an array of numbers
numbers = np.array([1, 4, 9, 16, 25])

# Apply the custom operation
result = custom_operation(numbers)

# Print the results
print("Original numbers:", numbers)
print("Result of custom operation:", result)


Original numbers: [ 1  4  9 16 25]
Result of custom operation: [1.64872127e+00 7.38905610e+00 9.00171313e+01 2.98095799e+03
 2.68337287e+05]


In [32]:
'''Solve a system of linear equation using numpy functions.'''

# Define the system of equations with coefficients matrix A and constants vector b
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 8])

# Solve the system using the np.linalg.solve function
solution = np.linalg.solve(A, b)

# Print the solution vector
print("Solution:", solution)


Solution: [1.4 2.2]


In [2]:
'''Write a user defined python function to create an array of size 5 and also take an 
integer value saperately.'''

import numpy as np

def create_and_fill_array(size, value):
 """
 This function creates a NumPy array of a given size and fills it with a specified value.

 Args:
   size: The desired size of the array.
   value: The value to fill the array with.

 Returns:
   A NumPy array of the specified size filled with the given value.
 """

 # Create the array
 array = np.zeros(size)

 # Fill the array with the value
 array[:] = value

 return array

# Example usage
array = create_and_fill_array(5, 10)
print(array)  # Output: [10 10 10 10 10]


[10. 10. 10. 10. 10.]


In [3]:
'''Write a user defined python function to create an array of size 5 and also
take an integer value saperately to find out the occurance of elements'''

import numpy as np

def find_element_occurrences(array, value):
  """
  This function takes a NumPy array and returns a dictionary containing the occurrences of each element.

  Args:
    array: A NumPy array.
    value: The integer value to find the occurrence of.

  Returns:
    A dictionary where the keys are the unique elements in the array and the values are their respective occurrences.
  """

  # Create an empty dictionary to store the occurrences
  occurrences = {}

  # Iterate through each element in the array
  for element in array:
    # Check if the element is already in the dictionary
    if element in occurrences:
      # Increment the occurrence count
      occurrences[element] += 1
    else:
      # Add the element to the dictionary with an occurrence count of 1
      occurrences[element] = 1

  # Return the occurrences of the specified value
  return occurrences.get(value, 0)  # Return 0 if the value is not found

# Example usage
array = np.array([1, 2, 2, 3, 1])
value_to_find = 2
occurrences = find_element_occurrences(array, value_to_find)
print("Occurrences of", value_to_find, ":", occurrences)  # Output: Occurrences of 2 : 2


Occurrences of 2 : 2


In [4]:
''' Write a user defined python function to create an array of size 5 and 
find a given number is present in the array or not.'''
import numpy as np

def is_element_present(array, value):
  """
  This function checks if a given value is present in a NumPy array using two methods.

  Args:
    array: A NumPy array.
    value: The integer value to search for.

  Returns:
    A tuple containing two booleans:
      - `in_operator`: True if the value is present using the "in" operator.
      - `any_method`: True if the value is present using the "any" method.
  """

  # Method 1: Using the "in" operator
  in_operator = value in array

  # Method 2: Using the "any" method
  any_method = np.any(array == value)

  return in_operator, any_method

# Example usage
array = np.array([1, 2, 3, 4, 5])
value_to_find = 3
present, present_any = is_element_present(array, value_to_find)
print("Is", value_to_find, "present in the array using 'in' operator:", present)
print("Is", value_to_find, "present in the array using 'any' method:", present_any)


Is 3 present in the array using 'in' operator: True
Is 3 present in the array using 'any' method: True


In [5]:
'''write a user defined python function to split an array and add the first part of the end.'''

import numpy as np

def split_and_add_first_to_end(array):
  """
  Splits an array into two parts and adds the first part to the end.

  Args:
      array: A NumPy array.

  Returns:
      A NumPy array with the first part added to the end.

  Raises:
      ValueError: If the input array is empty.
  """

  if len(array) == 0:
      raise ValueError("Input array cannot be empty.")

  # Split the array at its midpoint
  split_point = len(array) // 2
  first_part = array[:split_point]
  second_part = array[split_point:]

  # Combine the second part and the first part to form the modified array
  modified_array = np.concatenate((second_part, first_part))

  return modified_array

# Example usage
array = np.array([1, 2, 3, 4, 5])
modified_array = split_and_add_first_to_end(array)
print(modified_array)  # Output: [3 4 5 1 2]


[3 4 5 1 2]


In [6]:
'''Write a python function to find out the largest element in a given integers.'''

import numpy as np

def find_largest_element(array):
  """
  This function finds the largest element in a NumPy array of integers.

  Args:
    array: A NumPy array of integers.

  Returns:
    The largest element in the array.

  Raises:
    ValueError: If the input array is empty.
  """

  if len(array) == 0:
      raise ValueError("Input array cannot be empty.")

  # Use np.max to efficiently find the largest element
  largest_element = np.max(array)

  return largest_element

# Example usage
array = np.array([3, 5, 1, 7, 2])
largest = find_largest_element(array)
print("Largest element:", largest)  # Output: Largest element: 7


Largest element: 7


In [7]:
''' Write a user defined function to create two matrices and dimensions r1*c1 and r2*c2 and
add,substract and multiply them.'''

import numpy as np

def matrix_operations(matrix1, matrix2):
  """
  Performs addition, subtraction, and multiplication on two NumPy matrices.

  Args:
    matrix1: A NumPy matrix with dimensions r1*c1.
    matrix2: A NumPy matrix with dimensions r2*c2.

  Returns:
    A tuple containing three NumPy matrices:
      - sum_matrix: The sum of matrix1 and matrix2.
      - difference_matrix: The difference of matrix1 and matrix2.
      - product_matrix: The product of matrix1 and matrix2 (if possible).

  Raises:
    ValueError: If the dimensions of the matrices are not compatible for the operation.
  """

  # Check if dimensions are compatible for addition and subtraction
  if matrix1.shape != matrix2.shape:
    raise ValueError("Matrices must have the same dimensions for addition and subtraction.")

  # Check if dimensions are compatible for multiplication
  if matrix1.shape[1] != matrix2.shape[0]:
    raise ValueError("Inner dimensions must be equal for matrix multiplication.")

  # Perform addition
  sum_matrix = matrix1 + matrix2

  # Perform subtraction
  difference_matrix = matrix1 - matrix2

  # Perform multiplication
  product_matrix = np.matmul(matrix1, matrix2)

  return sum_matrix, difference_matrix, product_matrix

# Example usage
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

sum_matrix, difference_matrix, product_matrix = matrix_operations(matrix1, matrix2)

print("Sum matrix:\n", sum_matrix)
print("Difference matrix:\n", difference_matrix)
print("Product matrix:\n", product_matrix)


Sum matrix:
 [[ 6  8]
 [10 12]]
Difference matrix:
 [[-4 -4]
 [-4 -4]]
Product matrix:
 [[19 22]
 [43 50]]
